name: Update Cloudflare DNS

on:
  schedule:
    - cron: '30 0 * * *'  # 每天 UTC 08:00 运行
    - cron: '30 5 * * *'  # 每天 UTC 13:00 运行
    - cron: '30 10 * * *'  # 每天 UTC 18:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  update-dns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run DNS update script
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          ZONE_ID: ${{ secrets.ZONE_ID }}
          DOMAIN: ${{ secrets.DOMAIN }}
        run: python dns_updater.py